<?php

namespace App\Swagger;

/**
 * @OA\Post(
 *     path="/api/midtrans/webhook",
 *     summary="Midtrans Webhook Notification",
 *     description="Handle payment notification from Midtrans payment gateway",
 *     operationId="midtransWebhook",
 *     tags={"Webhooks"},
 *
 *     @OA\RequestBody(
 *         required=true,
 *         @OA\JsonContent(
 *             required={
 *                 "order_id",
 *                 "transaction_status",
 *                 "status_code",
 *                 "gross_amount",
 *                 "signature_key",
 *                 "payment_type",
 *                 "transaction_time",
 *                 "fraud_status"
 *             },
 *             @OA\Property(
 *                 property="order_id",
 *                 type="string",
 *                 example="TRX20251202ABC123",
 *                 description="Order ID generated by your system"
 *             ),
 *             @OA\Property(
 *                 property="transaction_status",
 *                 type="string",
 *                 example="settlement",
 *                 description="Status of the transaction"
 *             ),
 *             @OA\Property(
 *                 property="status_code",
 *                 type="string",
 *                 example="200",
 *                 description="Midtrans status code"
 *             ),
 *             @OA\Property(
 *                 property="gross_amount",
 *                 type="string",
 *                 example="500000",
 *                 description="Total transaction amount"
 *             ),
 *             @OA\Property(
 *                 property="signature_key",
 *                 type="string",
 *                 example="abc123def456...",
 *                 description="Security signature for validation"
 *             ),
 *             @OA\Property(
 *                 property="payment_type",
 *                 type="string",
 *                 example="qris",
 *                 description="Payment method used by user"
 *             ),
 *             @OA\Property(
 *                 property="transaction_time",
 *                 type="string",
 *                 example="2025-12-02 18:00:00",
 *                 description="Payment transaction time"
 *             ),
 *             @OA\Property(
 *                 property="fraud_status",
 *                 type="string",
                 example="accept",
 *                 description="Fraud detection status"
 *             )
 *         )
 *     ),
 *
 *     @OA\Response(
 *         response=200,
 *         description="Webhook processed successfully",
 *         @OA\JsonContent(
 *             @OA\Property(property="status", type="string", example="success"),
 *             @OA\Property(property="message", type="string", example="Payment notification processed")
 *         )
 *     ),
 *
 *     @OA\Response(
 *         response=400,
 *         description="Invalid signature or request"
 *     )
 * )
 */
class WebhookSwagger {}
